### ISSUE TITLE
How to use in java code?

### ISSUE THREAD

**Issue by NanyangTaiji** [Udhayarajan/VidSnapKit-Ultimate#1]
val extractor = Extractor.findExtractor("https://www.instagram.com/p/B_5qXN6j5sd")
extractor?.let {
                cookies?.let { cookie ->
                    it.cookies = cookie
                }
                it.start { res ->
                    //Get data from here
                }
            }

**Comment by Udhayarajan** [comment]
You can refer to [this ](https://github.com/Udhayarajan/VidSnapKit/blob/master/sample%20app/src/main/java/com/mugames/vidsnapkit/MainActivityJava.java)Android Java file for Java Implementation. If you are from a non-Android background kindly focus on [onClick ](https://github.com/Udhayarajan/VidSnapKit/blob/65e636060b6cdc085e0470b9513f793064837b32/sample%20app/src/main/java/com/mugames/vidsnapkit/MainActivityJava.java#L67)method and [progressCallback ](https://github.com/Udhayarajan/VidSnapKit/blob/65e636060b6cdc085e0470b9513f793064837b32/sample%20app/src/main/java/com/mugames/vidsnapkit/MainActivityJava.java#L36) property.
