### ISSUE TITLE
Failed to resolve: io.github.udhayarajan:VidSnapKit:4.0.3

### ISSUE THREAD

**Issue by NewMacPro** [Udhayarajan/VidSnapKit-Ultimate#3]
Failed to resolve: io.github.udhayarajan:VidSnapKit:4.0.3
what can I do?

**Comment by Udhayarajan** [comment]
Make sure you have included

```
repositories {
    mavenCentral()
}
```

**Comment by NewMacPro** [comment]
https://vimeo.com/783455041

I get a error


failed to get stream info: ERROR: [vimeo] 22439234: Unable to download webpage: <urlopen error _ssl.c:1091: The handshake operation timed out> (caused by URLError(timeout('_ssl.c:1091: The handshake operation timed out')))



Thanks

**Comment by Udhayarajan** [comment]
@NewMacPro is your `Failed to resolve: io.github.udhayarajan:VidSnapKit:4.0.3` resolved? Kindly post other issues in a separate issue thread.

**Comment by NewMacPro** [comment]
I first just use your vidsnap.apk to try. https://github.com/Udhayarajan/VidSnap/releases
[VidSnap.6.0.0.apk](https://github.com/Udhayarajan/VidSnap/releases/download/v6.0.0(13)-release/VidSnap.6.0.0.apk)
I get an error

**Comment by Udhayarajan** [comment]
I'm marking it as closed because if you get the error `io.github.udhayarajan: VidSnapKit:4.0.3` in [VidSnap](https://github.com/Udhayarajan/VidSnap). It might be a gradle problem in that repo not in this.
