### ISSUE TITLE
vimeo not work

### ISSUE THREAD

**Issue by NewMacPro** [Udhayarajan/VidSnapKit-Ultimate#4]
I first just use your vidsnap.apk to try. https://github.com/Udhayarajan/VidSnap/releases
[VidSnap.6.0.0.apk](https://github.com/Udhayarajan/VidSnap/releases/download/v6.0.0(13)-release/VidSnap.6.0.0.apk)
I get an error

https://vimeo.com/783455041

I get a error

failed to get stream info: ERROR: [vimeo] 22439234: Unable to download webpage: (caused by URLError(timeout('_ssl.c:1091: The handshake operation timed out')))

**Comment by Udhayarajan** [comment]
The error is that your net connection is slow. Have you checked with some fast internet? I have also checked it out with my [server](https://rapidapi.com/mudhayarajan2013/api/vidsnap)

**Comment by Udhayarajan** [comment]
closing this issue as there is no further information
