### ISSUE TITLE
Twitter link not work Error says:Bad Authentication data.

### ISSUE THREAD

**Issue by Asif-Codify** [Udhayarajan/VidSnapKit-Ultimate#7]
Twitter video link not work always says Bad Authentication data. Please check and fix this

**Comment by Udhayarajan** [comment]
Can you please give me 2-3 sample URLs?

**Comment by Udhayarajan** [comment]
Due to Twitter's unpredictable behaviour right now it's hard to find the extraction logic. Soon it will be fixed once the Twitter becomes stable. 
Follow up on the issue from here.
https://github.com/ytdl-org/youtube-dl/issues/32392#issuecomment-1616839318
